import { TrendDataPoint, VitalReading, VocRiskStatus } from './mockData';

/**
 * Canonical incoming wearable payload contract from Dylan's PicoW-BLE hardware.
 *
 * Example payloads:
 *   {"heartRate":72,"spo2":98,"hbTrendIndex":81.20,"battery":84,"fingerDetected":true}
 *   {"heartRate":0,"spo2":0,"hbTrendIndex":0.00,"fingerDetected":false}
 *   {"heartRate":68,"spo2":97,"hbTrendIndex":79.80,"fingerDetected":true}
 *
 * Rules:
 *  - hbTrendIndex is a relative trend index on a 0.00–99.99 scale. Not absolute hemoglobin.
 *  - battery may be omitted; preserve last known value rather than zeroing.
 *  - fingerDetected=false means the sensor is idle; heartRate/spo2/hbTrendIndex
 *    will be 0 and must NOT be treated as real physiological values.
 *  - timestamp is generated by the app on receipt (hardware does not send one).
 */
export interface WearableSnapshotPayload {
  deviceId?: string;
  timestamp?: string;
  heartRate?: number;
  spo2?: number;
  hbTrendIndex?: number;
  battery?: number;
  fingerDetected?: boolean;
}

export interface NormalizedWearableSnapshot {
  deviceId: string;
  timestamp: string;
  heartRate: number;
  spo2: number;
  /** Relative hemoglobin trend index from hardware. Scale 0.00–99.99. Not absolute hemoglobin. */
  hbTrendIndex: number;
  battery?: number;
  /** True when a finger is placed on the sensor and values are valid. */
  fingerDetected: boolean;
}

const FALLBACKS = {
  deviceId: 'PicoW-BLE-UNKNOWN',
  heartRate: 74,
  spo2: 97,
  hbTrendIndex: 80.0,   // representative value on the 0–99.99 hardware scale
  temperatureF: 98.6,
  hydrationLabel: 'Optimal',
};

const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

function toFiniteOrFallback(value: number | undefined, fallback: number) {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return fallback;
  }
  return value;
}

function clamp(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, value));
}

function decodeBytePayload(payload: Uint8Array): string {
  return new TextDecoder().decode(payload);
}

function parseJsonObject(text: string): Record<string, unknown> {
  try {
    const parsed = JSON.parse(text);
    if (parsed && typeof parsed === 'object') {
      return parsed as Record<string, unknown>;
    }
  } catch (_error) {
    // Ignore parse errors and fall back to defaults.
  }
  return {};
}

function toOptionalFiniteNumber(value: unknown): number | undefined {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value;
  }

  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }

  return undefined;
}

function toOptionalString(value: unknown): string | undefined {
  if (typeof value !== 'string') {
    return undefined;
  }

  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function toBoolean(value: unknown, defaultValue: boolean): boolean {
  if (typeof value === 'boolean') return value;
  if (value === 1 || value === '1' || value === 'true') return true;
  if (value === 0 || value === '0' || value === 'false') return false;
  return defaultValue;
}

/**
 * Single parser/normalizer for raw device payloads.
 * Accepts unknown input and returns a safe internal snapshot.
 *
 * When fingerDetected is false, heartRate/spo2/hbTrendIndex are preserved as
 * zero (matching hardware behavior). Callers must gate on fingerDetected.
 */
export function parseAndNormalizeWearableSnapshot(
  payload: unknown
): NormalizedWearableSnapshot {
  const raw = (() => {
    if (typeof payload === 'string') {
      return parseJsonObject(payload);
    }

    if (payload instanceof Uint8Array) {
      return parseJsonObject(decodeBytePayload(payload));
    }

    if (payload instanceof ArrayBuffer) {
      return parseJsonObject(decodeBytePayload(new Uint8Array(payload)));
    }

    if (payload !== null && typeof payload === 'object') {
      return payload as Record<string, unknown>;
    }

    return {};
  })();

  const fingerDetected = toBoolean(raw.fingerDetected, true);

  // Timestamp: hardware doesn't send one — use current time or fallback.
  const timestampCandidate = toOptionalString(raw.timestamp);
  const timestamp =
    timestampCandidate && Number.isFinite(Date.parse(timestampCandidate))
      ? timestampCandidate
      : new Date().toISOString();

  const batteryCandidate = toOptionalFiniteNumber(raw.battery);

  // When finger is not detected, heartRate/spo2/hbTrendIndex will be 0.
  // We preserve them as-is so callers can inspect them, but callers MUST
  // check fingerDetected before displaying or using these values.
  const heartRate = fingerDetected
    ? clamp(
        toFiniteOrFallback(
          toOptionalFiniteNumber(raw.heartRate),
          FALLBACKS.heartRate
        ),
        35,
        220
      )
    : toFiniteOrFallback(toOptionalFiniteNumber(raw.heartRate), 0);

  const spo2 = fingerDetected
    ? clamp(
        toFiniteOrFallback(
          toOptionalFiniteNumber(raw.spo2),
          FALLBACKS.spo2
        ),
        70,
        100
      )
    : toFiniteOrFallback(toOptionalFiniteNumber(raw.spo2), 0);

  // hbTrendIndex is on a 0.00–99.99 scale from hardware.
  const hbTrendIndex = fingerDetected
    ? clamp(
        toFiniteOrFallback(
          toOptionalFiniteNumber(raw.hbTrendIndex),
          FALLBACKS.hbTrendIndex
        ),
        0.0,
        100.0
      )
    : toFiniteOrFallback(toOptionalFiniteNumber(raw.hbTrendIndex), 0);

  return {
    deviceId: toOptionalString(raw.deviceId) ?? FALLBACKS.deviceId,
    timestamp,
    heartRate,
    spo2,
    hbTrendIndex,
    battery:
      typeof batteryCandidate === 'number'
        ? clamp(batteryCandidate, 0, 100)
        : undefined,
    fingerDetected,
  };
}

/**
 * Backward-compatible alias.
 */
export const normalizeWearableSnapshotPayload = parseAndNormalizeWearableSnapshot;

function buildHydrationLabel(spo2: number, heartRate: number): string {
  if (spo2 <= 94 || heartRate >= 105) {
    return 'Low';
  }
  if (spo2 <= 96 || heartRate >= 90) {
    return 'Fair';
  }
  return FALLBACKS.hydrationLabel;
}

/**
 * Returns the metric value for a given snapshot.
 * For 'hemoglobin', returns hbTrendIndex directly (not a derived g/dL).
 */
export function getWearableMetricValue(
  snapshot: NormalizedWearableSnapshot,
  metricId: string
): number {
  if (metricId === 'hemoglobin') {
    return snapshot.hbTrendIndex;
  }
  if (metricId === 'heartRate') {
    return snapshot.heartRate;
  }
  if (metricId === 'temperature') {
    return FALLBACKS.temperatureF;
  }
  return snapshot.spo2;
}

function getVitalStatus(value: number, min: number, max: number): VitalReading['status'] {
  if (value < min || value > max) {
    return 'alert';
  }
  const lowerCaution = min + (max - min) * 0.1;
  const upperCaution = max - (max - min) * 0.1;
  if (value < lowerCaution || value > upperCaution) {
    return 'caution';
  }
  return 'optimal';
}

export function mapHardwareSnapshotToVitals(
  snapshot: NormalizedWearableSnapshot
): VitalReading[] {
  const noReading = !snapshot.fingerDetected;

  const vitals: VitalReading[] = [
    {
      label: 'Blood Oxygen',
      value: noReading ? '—' : Math.round(snapshot.spo2),
      unit: noReading ? '' : '%',
      icon: 'water-outline',
      status: noReading ? 'optimal' : getVitalStatus(snapshot.spo2, 95, 100),
      normalRange: '95–100',
    },
    {
      label: 'Heart Rate',
      value: noReading ? '—' : Math.round(snapshot.heartRate),
      unit: noReading ? '' : 'bpm',
      icon: 'heart-pulse',
      status: noReading ? 'optimal' : getVitalStatus(snapshot.heartRate, 60, 100),
      normalRange: '60–100',
    },
    {
      label: 'Temperature',
      value: FALLBACKS.temperatureF,
      unit: '°F',
      icon: 'thermometer',
      status: 'optimal',
      normalRange: '97.8–99.1',
    },
    {
      label: noReading ? 'No Reading' : 'Hydration',
      value: noReading ? '—' : buildHydrationLabel(snapshot.spo2, snapshot.heartRate),
      unit: '',
      icon: noReading ? 'hand-wave-outline' : 'water',
      status: 'optimal',
    },
  ];

  if (typeof snapshot.battery === 'number') {
    vitals.push({
      label: 'Battery',
      value: Math.round(snapshot.battery),
      unit: '%',
      icon: 'battery-medium',
      status:
        snapshot.battery < 20
          ? 'alert'
          : snapshot.battery < 40
          ? 'caution'
          : 'optimal',
    });
  }

  return vitals;
}

export function mapHardwareSnapshotToRisk(
  snapshot: NormalizedWearableSnapshot
): VocRiskStatus {
  // No finger on sensor — do not derive risk from zero values.
  if (!snapshot.fingerDetected) {
    return {
      level: 'low',
      label: 'NO DATA',
      description:
        'Place finger on sensor for live VOC risk assessment.',
    };
  }

  if (snapshot.spo2 <= 93 || snapshot.heartRate >= 115) {
    return {
      level: 'high',
      label: 'HIGH RISK',
      description:
        'One or more indicators are outside safe thresholds. Prompt clinical follow-up is recommended.',
    };
  }

  if (snapshot.spo2 <= 95 || snapshot.heartRate >= 95) {
    return {
      level: 'moderate',
      label: 'MODERATE RISK',
      description:
        'Mild drift detected in current wearable indicators. Continue hydration protocol and monitor closely.',
    };
  }

  return {
    level: 'low',
    label: 'LOW RISK',
    description:
      'Current wearable indicators appear stable. Continue routine hydration and medication guidance.',
  };
}

export function mapHardwareSnapshotToTrendHistory(
  snapshot: NormalizedWearableSnapshot,
  metricId: string,
  range: 'day' | 'week' | 'month'
): TrendDataPoint[] {
  const points = range === 'day' ? 6 : range === 'week' ? 7 : 30;
  const parsedTimestamp = Date.parse(snapshot.timestamp);
  const minuteSeed = Number.isFinite(parsedTimestamp)
    ? new Date(parsedTimestamp).getUTCMinutes() % 5
    : 0;

  const pattern = [-0.6, -0.3, -0.1, 0, 0.2, 0.4, 0.1];

  const baseByMetric: Record<string, number> = {
    hemoglobin: getWearableMetricValue(snapshot, 'hemoglobin'),
    spo2: getWearableMetricValue(snapshot, 'spo2'),
    heartRate: getWearableMetricValue(snapshot, 'heartRate'),
    temperature: getWearableMetricValue(snapshot, 'temperature'),
  };

  const base = baseByMetric[metricId] ?? baseByMetric.spo2;

  // Scale variation to match each metric's natural range.
  // hbTrendIndex is 0–100 scale, so use ~±3 variation to look realistic.
  const scaleByMetric: Record<string, number> = {
    hemoglobin: 3.0,
    spo2: 0.8,
    heartRate: 2.8,
    temperature: 0.18,
  };
  const scale = scaleByMetric[metricId] ?? 1;

  return Array.from({ length: points }, (_, i) => {
    const dayIndex = i % DAY_LABELS.length;
    const wave = pattern[(i + minuteSeed) % pattern.length];
    const raw = base + wave * scale;
    const value = Math.round(raw * 10) / 10;

    return {
      date: DAY_LABELS[dayIndex],
      value,
    };
  });
}
